### ISSUE TITLE
[Suggestion] Remove Game.ini

### ISSUE THREAD

**Issue by Jamie96ITS** [dkdue/WindowsGSM.LastOasis#1]
It is unnecessary to work with Game.ini, as all of those settings are set per oasis via the web config, and sent to the node by the service when the node is instructed which oasis to load.

**Comment by dkdue** [comment]
You're absolutely right, when I come back from vacation, I'll take it off

**Comment by dkdue** [comment]
Thank you, you have saved me work, I have not been able to do much more due to my holidays, but with your help it seems that it works perfectly and the servers stay Online, a greeting
