### ISSUE TITLE
fix for 'Disconnected from host' when trying to join a tile from lobby

### ISSUE THREAD

**Issue by eorvedal** [dkdue/WindowsGSM.LastOasis#3]
find the line just after //Get WAN IP from net and change 
`string externalIpString = new WebClient().DownloadString("https://ipv4.icanhazip.com").Replace("\\r\\n", "").Replace("\\n", "").Trim();`

**Comment by dkdue** [comment]
ok, I've already changed it, if it works correctly adding https://ipv4 I'll leave it that way, but it might work adding S to http, I don't have the server installed and I haven't been able to check it, the changes are already made, thanks for The advertisement

**Comment by eorvedal** [comment]
the original line was returning an ipv6 which the game wasn't handling correctly. this will get just the standard ipv4 which corrected the problem on my end.

**Comment by dkdue** [comment]
Close

**Comment by dkdue** [comment]
Close
