### ISSUE TITLE
API Change for Season 5

### ISSUE THREAD

**Issue by Charly3o3** [dkdue/WindowsGSM.LastOasis#5]
Hi mate,

thank you for the nice WindowsGSM Last Oasis config! :-)

With Season 5 you have to change the entry in Line 71 of LastOasis.cs:

-backendapiurloverride=backend.last-oasis.com

has changed in to 

-backendapiurloverride=backend-production.last-oasis.com

Kind regards,

Charly

**Comment by dkdue** [comment]
Thanks for the warning, it has been changed
